### ISSUE TITLE
Next.js client-side error on production in the version 4.3.0

### ISSUE THREAD

**Issue by icaronowcm** [andreizanik/cookies-next#81]
"In this new update '4.3.0,' the library started throwing a new error in production. I fixed the version to '4.2.1,' and the error was gone!"

2117-15fb04c807f265ba.js:1 TypeError: argument name is invalid
    at t.serialize (8669-d0ad87f3fcb942d0.js:1:38692)
    at t.setCookie (8669-d0ad87f3fcb942d0.js:1:42580)
    at layout-d5ef98a14567a2c8.js:1:23308
    at aW (fd9d1056-e1f8238183e3a8d9.js:1:73244)
    at oe (fd9d1056-e1f8238183e3a8d9.js:1:84685)
    at ol (fd9d1056-e1f8238183e3a8d9.js:1:85323)
    at or (fd9d1056-e1f8238183e3a8d9.js:1:85207)
    at ol (fd9d1056-e1f8238183e3a8d9.js:1:86268)
    at or (fd9d1056-e1f8238183e3a8d9.js:1:85207)
    at ol (fd9d1056-e1f8238183e3a8d9.js:1:85303)

**Comment by enchorb** [comment]
+1 getting this as well

**Comment by bjarn** [comment]
I also stumbled on this issue. I used characters such as a semicolon in my key. Apparently, this is incompatible with the recent bump of `cookies` (https://github.com/andreizanik/cookies-next/pull/80).

See: https://github.com/jshttp/cookie/pull/167

For me, changing the key to something else (in this case I used an underscore) fixed it.
